### ISSUE TITLE
PS4-waker: “Could not detect any matching PS4 device” 

### ISSUE THREAD

**Issue by SmallDoseOfTruth** [dhleong/ps4-waker#100]
I'm not sure if you would be able to help, but I'm going to try anyways. I'm trying to use ps4-waker on hass.io following this guide: https://community.home-assistant.io/t/playstation-4-ps4-custom-component/16974/73

My problem is that when I SSH into the RPi and run ps4-waker, everything works fine. When I try to go to http://HA_IP_ADDRESS:3031/ps4/PS4_IP_ADDRESS/info, I'm getting a json {"status":"Could not detect any matching PS4 device"}.

It seems like a network issue, but I confirmed that both my RPi and my PS4 are on the same network so I don't think using --bind would help.

**Comment by SmallDoseOfTruth** [comment]
I am dyslexic. It works. Sorry and thank you.

**Comment by dhleong** [comment]
No problem, glad you figured it out! Would you mind commenting briefly what the issue was in case anyone from the future runs into the same thing?
