### ISSUE TITLE
Error:  Cannot find module './dist/detector'

### ISSUE THREAD

**Issue by darkdataflow** [dhleong/ps4-waker#101]
I have node.js 11.x but getting this error when trying to run ps4-waker. Any thoughts?

To clarify, I ran the following:
git clone https://github.com/dhleong/ps4-waker.git
sudo npm i ps4-waker -g
sudo ps4-waker --help

which gives the error message

**Comment by dhleong** [comment]
I just tested a fresh install and it works fine here.

You don't need to clone the repo if you're just running the executable (or even if you're using it in a library). Are you sure you didn't run `./index.js`? That would explain `/dist` not existing, and means you need compile the library with `npm run build`

**Comment by darkdataflow** [comment]
I know nothing about linux and have just been trying to google my way through.

I'm going to fresh install without cloning and report back.

**Comment by darkdataflow** [comment]
Not cloning the repo worked. Thank you!
