### ISSUE TITLE
Quick question regarding changing the credentials file

### ISSUE THREAD

**Issue by darkdataflow** [dhleong/ps4-waker#102]
I have a really stupid question but didn't know where else to ask.

When I initially installed, I credentialed on the wrong PS4 account (i.e. used the wrong PS4 account on the Second Screen App). What is the easiest way to change the credentials? Would it be to run the setup again?

I don't even know where the current credentials file is located. I just type "ps4-waker" and it works, I am not specifying a specific location for the credentials file.

**Comment by dhleong** [comment]
See [this wiki page](https://github.com/dhleong/ps4-waker/wiki#credentials) about the default credentials location. The easiest way to change the default credentials is to just delete that file.

Alternatively, you can use the `-c` flag to specify a location to put the credentials, and `ps4-waker` should prompt you to create them if they don't exist
