### ISSUE TITLE
Second Screen App Not Seeing PS4-Waker

### ISSUE THREAD

**Issue by dontKnowWhatIAmDoin** [dhleong/ps4-waker#103]
I am a complete novice so I apologize in advance for any of my mistakes.
 
I have been trying to set ps4-waker on my MacBook. I am currently running into [this issue](https://github.com/dhleong/ps4-waker/issues/76). I cannot find [the files refrenced in this comment](https://github.com/dhleong/ps4-waker/issues/76#issuecomment-357791270) & am unaware of how to install anything as root. 

Due to reading [this issue](https://github.com/dhleong/ps4-waker/issues/27) I have tried solving it through my router but have had no luck. I have input the port forwarding numbers into the google wifi router using the app but am not seeing any difference. Routers are also something I am a complete novice with so I am not sure if I am doing it correctly. [Here is a screenshot of what I am doing in regards to the port forwarding.](https://i.imgur.com/TUj6Q43.jpg)
I have tried setting up the port forwarding numbers for both the MacBook & the iPhone. 

If I am missing anything or should read anything that I may have missed that could help me with this issue please let me know. 
Thank you.

**Comment by dhleong** [comment]
Your router won't help you if you're getting the "root permissions needed" error, so don't worry about that yet. Also, if you can run `ps4-waker` at all, you should be in good shape; you don't need to install anything else as root.

All you need to do is run `sudo ps4-waker` in the command line. That should get you started. If you see an error, please copy and paste it here.

**Comment by dontKnowWhatIAmDoin** [comment]
sudo: ps4-waker: command not found

This is what I am getting when I run sudo ps4-waker in the command line.

**Comment by dhleong** [comment]
Okay it sounds like you didn't install `ps4-waker` via `npm`? How did you run it to get the "root" error?

**Comment by dontKnowWhatIAmDoin** [comment]
If I recall correctly I just opened it via finder. How would i go about deleting it & starting from scratch to install it correctly this time?

**Comment by dontKnowWhatIAmDoin** [comment]
'npm i ps4-waker -g
⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ rollbackFailedOptional: verb npm-session 0a02df61a6115bab'

This is what i get when i run the install comman in the terminal. It doesnt do anything but load after that. 

In order to get the root error I just run `npx ps4-waker`

**Comment by dhleong** [comment]
Glad you figured it out!
