### ISSUE TITLE
Error 23 / Login failed

### ISSUE THREAD

**Issue by mensa84** [dhleong/ps4-waker#109]
Hello,

I am unable to connect my PS4 second screen App with ps4-waker.
Did the following:
Turn on PS4
Launch PS4 second screen App on my iPhone
* rm ~/.ps4-wake.credentials.json
* ps4-waker
* Connect to ps4-waker from PS4 second screen App from my iPhone via second screen menu
* Credentials are received
* goto Settings->PSApp Connection Settings -> Add Device
* Enter 8 digit passcode
* LOGIN_FAILED

Always get that error after entering the PIN from PS4 menu to ps4-waker:
```
root@Server:~# ps4-waker
No credentials; Use the PS4 Second Screen App and try to connect to PS4-Waker
Got credentials!  { 'client-type': 'i',
  'auth-type': 'C',
  'user-credential':
   '1c5331890f822c43fbca73716eb8a4ab59b75e1155b92c75998b1cb72082e16b' }
Go to 'Settings -> Mobile App Connection Settings -> Add Device' on your PS4 to obtain the PIN code.
Pin code> 48633651
Unexpected error:23 / LOGIN_FAILED
```

Can you please help me?

**Comment by mensa84** [comment]
The problem is solved.
I was in the wrong menu on the PS4 (at remote play menu instead of mobile app).
Sorry for confusion.

**Comment by dhleong** [comment]
No problem, glad you got it working!
