### ISSUE TITLE
Multiple interface

### ISSUE THREAD

**Issue by realPy** [dhleong/ps4-waker#11]
When we have multiple interface like a vpn, the default interface is used to broadcast.
Can you add an option to specify the interface to broadcast?

Thks :)

**Comment by dhleong** [comment]
I might be able to look into it if I have time. Would you provide a string
like "eth2," I presume?

**Comment by realPy** [comment]
No i'll read the doc of nodejs it said :
"the address argument is a string. If the value of address is a host name, DNS will be used to resolve the address of the host. If the address is not specified or is an empty string, '127.0.0.1' or '::1' will be used instead.

If the socket has not been previously bound with a call to bind, the socket is assigned a random port number and is bound to the "all interfaces" address ('0.0.0.0' for udp4 sockets, '::0' for udp6 sockets.)"

So to send packet with a specific interface you must provide the ip of the interface with just a bind after socket create with the good ip :)

socket.bind({
  address: 'localhost',
  port: 8000,
  exclusive: true
});

**Comment by realPy** [comment]
Just clone and modify detector.js line 16
modify the bind function with my ip adress like: 
s.bind({
          address: '192.168.1.78'},function() {
        s.setBroadcast(true);


Detection works succesfull.
Never code in nodejs so i think i'll wait you modify.
I can fork and modify but i think it will me take more time to learn node ;)
thks in advance!

**Comment by realPy** [comment]
Ok i'll begin to see.
nodejs is easy i'll end you the merge request when it's ready ;)

**Comment by realPy** [comment]
Pull request done.

**Comment by dhleong** [comment]
I've merged your commits with my refactors. Thanks!
