### ISSUE TITLE
Second Screen app does not find PS4-Waker

### ISSUE THREAD

**Issue by Crox77** [dhleong/ps4-waker#112]
Please help

I have installed PS4 Waker ok on my Mac, when I run the second screen app, it does not find PS4 Waker only my actual PS4.
Don't know what the problem is! 
Any Ideas please?

**Comment by dhleong** [comment]
Please provide some more context. What does the output from `ps4-waker` look like? What's your network situation—eg: is your Mac on Wifi, or plugged into ethernet?

**Comment by Crox77** [comment]
Hi Thank you for your reply, I have no idea what you mean by my output from PS4 waker is but when I run PS4-Waker in Terminal I get this Crox-iMac:~ Crox-iMac$ ps4-waker
WAKEUP sent to device... 192.168.0.22
Logging in...
Go to 'Settings -> Mobile App Connection Settings -> Add Device' on your PS4 to obtain the PIN code.

As for Network, im connected to my WIFi and the Ethernet cable is plugged in
Thanks Paul

**Comment by Crox77** [comment]
However when I do what it says and run the Second screen app it does nothing

**Comment by dhleong** [comment]
Okay, so what's probably happening is your Mac has two network adapters, so you'll need to use this flag so your phone can see your Mac:

```
  --bind | -b <ip>             Bind to a specific network adapter IP, if you have multiple
```

To figure out what to use in place off `<ip>` you'll want to open `System Preferences > Network` and select your WiFi connection. On the right side under "Status" it should say your Wifi IP address. Then, for example, if your IP address shows `192.168.0.22` you'll want to run `ps4-waker` like this:

  sudo ps4-waker --bind 192.168.0.22

You shouldn't need to use that flag once you register successfully with the device—I don't from my Mac Mini, which also is on both wifi and ethernet—but if it doesn't work after the initial registration it's worth a shot.

**Comment by Crox77** [comment]
ok so I run this

Crox-iMac:~ Crox-iMac$ sudo ps4-waker --bind 192.168.0.10
WAKEUP sent to device... 192.168.0.22
Logging in...
Go to 'Settings -> Mobile App Connection Settings -> Add Device' on your PS4 to obtain the PIN code.
Crox-iMac:~ Crox-iMac$ 
cant get ps4 waker to start so it can be found by my phone, is that right?

**Comment by dhleong** [comment]
Okay I looked closer at your output. It looks like ps4-waker has already logged into your PS4 before? If you don't have any credentials it should prompt you to run with `sudo` and connect to it with your phone, but it's not doing that, so you don't need your phone.

It looks like it's not actually prompting you to input the pin code, which is a bug. But, you should be able to resolve it by re-registering.

1. Delete your old credentials file: `rm ~/.ps4-wake.credentials.json`
2. Run `sudo ps4-waker`. It should prompt you to connect with your phone
3. ps4-waker should then prompt you as above to obtain a PIN code. Do as requested on your PS4 and type it in, then hit enter.

It should then login and you should get output that looks like "Logged into device! Future uses should succeed"

**Comment by Crox77** [comment]
thank you Daniel that worked, however just to check it now comes up on my ps4 connected then disconnected, is this right?

**Comment by dhleong** [comment]
Glad it's all working!

That's correct. `ps4-waker` connects as a companion app briefly to sign you in and perform any other signin-required tasks, such as `ps4-waker standby`, or sending keys, starting apps, etc. So, you'll see it pop up as connected for like a second while it does its thing, then disconnect immediately after.

**Comment by brunooor** [comment]
Hello dhleong, i'm with the similar problem, when i use comand "ps4-waker" on Node.js command prompt, i'v received the follow message:

No credentials; Use the PS4 Second Screen App and try to connect to "PS4-Waker"
"PS4-Waker" device should now be available...

but PS4-Waker isn't displayed in the app Second Screen, i use Windows instead of MAC. The ps4-waker has already logged into my PS4 before, and i accidentally delete the device conection on PS4. How can i follow similar steps on Windows ?

**Comment by dhleong** [comment]
@brunooor Have you checked this thread: https://github.com/dhleong/ps4-waker/issues/63

**Comment by brunooor** [comment]
> @brunooor Have you checked this thread: #63

I h've checked, isn't that especific problem, but a mess where my computer was seeing my Network how a public Network, and i just had able firewall to private Network. I h've corrected this on advanced setings  of Firewall and now all working fine !! :) 

Thank you for your Support.

**Comment by dhleong** [comment]
Thanks for the update! I'll add that info to the wiki for future Windows users :)
