### ISSUE TITLE
Issue with initial login

### ISSUE THREAD

**Issue by denisrosenkranz** [dhleong/ps4-waker#115]
Hello,

I'm not able to perform the initial login. I got this error:

`root@MyServer:~# ps4-waker
WAKEUP sent to device... 192.168.2.44
Logging in...
Go to 'Settings -> Mobile App Connection Settings -> Add Device' on your PS4 to obtain the PIN code.
Pin code> XXXXXXXX
(node:2601) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'login' of null
    at /usr/lib/node_modules/ps4-waker/dist/cli/base.js:268:12
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/lib/node_modules/ps4-waker/dist/cli/base.js:5:103)
    at _next (/usr/lib/node_modules/ps4-waker/dist/cli/base.js:7:194)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:2601) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2601) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
Is it an issue with my NodeJS version?

node -v ==> v8.12.0
nodejs -v ==> v8.12.0

Thanks,

**Comment by dhleong** [comment]
Thanks for reporting this. It's a bug.

**Comment by dhleong** [comment]
@denisrosenkranz Try again with 1.8.2; let me know if it's not resolved, but it's working here.

**Comment by denisrosenkranz** [comment]
Cool thanks! I'll try it this evening.

**Comment by denisrosenkranz** [comment]
Yes I confirm It's working ! Thanks that was a quick fix !

**Comment by dhleong** [comment]
👍 No problem :)
