### ISSUE TITLE
Possible to maintain infinite connection to PS4?  (re: home automation)

### ISSUE THREAD

**Issue by sofakng** [dhleong/ps4-waker#119]
Is it possible to create an "infinite" connection with the PS4 with the NodeJS library?

For example, I'd like to basically run ps4-waker in "server" mode where it connects to a PS4 and waits for commands.  If it failed connection it would automatically re-try every few seconds, and automatically reconnect if disconnected.

I know this behavior isn't built-in to ps4-waker, but could it either be added in the future, or could I create something similar using the provided ps4-waker NodeJS library?

**Comment by dhleong** [comment]
This type of functionality is provided in the NodeJS lib via the [Device API](https://github.com/dhleong/ps4-waker/blob/master/lib/device.js). There's some terrible code in [my home automation setup](https://github.com/dhleong/my-home2/blob/master/modules/ps4.js) that demonstrates the basic use.

**Comment by GuccW6** [comment]
Can I use the 'terrible code' as is to avoid relentless companion app connection and disconnection messages when switching between games? Do I copy and paste in a file named ps4.js and then place somewhere?

**Comment by dhleong** [comment]
You can use it as a start, but @GuccW6 it'll be much easier for you to spend a couple days learning Javascript + nodejs. I'm happy to help if you have specific questions on how things work, but I can't walk you through every step.
