### ISSUE TITLE
Using ps4-waker without root

### ISSUE THREAD

**Issue by Sinled** [dhleong/ps4-waker#122]
Hi, 
i would like to use `ps4-waker` with [athom homey controller ](https://www.athom.com/en/homey/)

The problem is that it is not possible to run cli on it, and root privileges are also unavailable -  application is just node package which evaluated inside their sandbox.

So my question is there any chances to make it work on such controller? 
I've tried to receive credentials file on my mac, and then use it in homey, but it seems that credentials are device specific, and will not work on another device.

**Comment by dhleong** [comment]
Credentials are indeed device specific. You could try spoofing your mac's MAC address to be that of the homey device and create credentials that way? 

Unfortunately part of the registration protocol requires the use of certain privileged ports, so unless homey's sandbox lets you use those ports without root it would not be possible to do that step on the device itself even if you did have CLI access....

**Comment by Sinled** [comment]
Thanks for idea, i can try this.
