### ISSUE TITLE
Can’t change state in homebridhe

### ISSUE THREAD

**Issue by Smexhy** [dhleong/ps4-waker#123]
Hello, I just installed your plugin on my already running homebridge. 

Everyrhing went fine. After installing your plugin, setting up config and restarting homebridge I immediately found PS4 in my homekit app. Unfortunately I can see just it’s state (turned on/off) but I can’t change it. When I click to change it, it will just load but won’t do anything.

What I tried is to write serial number with and then without “-“ in numbers, but it seems it didn’t help. I checked twice, but my model and serial number is correct. I have only one PS4 so I didn’t set up static lease on IP for the ps4. Using latest firmware and homebridge. Where could be the problem?

Checked logs but all I found regarding PS4Waker was successfully finding my PS4 at the boot. No errors at all.

Here is some screen share for better understanding: https://imgur.com/a/bzQg81p

Also sorry I am writing here, I couldn’t find ps4 waker github directly for homebridge, as I am getting 404 page there.

Thanks

**Comment by dhleong** [comment]
Unfortunately I have nothing to do with homebridge so the support I can provide is pretty limited. Have you tried using `ps4-waker` directly via the command line? Does it work there? If not, what error does it show? Have you followed the [troubleshooting](https://github.com/dhleong/ps4-waker/wiki/Troubleshooting) guide?

I don't know about homebridge, but ps4-waker doesn't use serial numbers, but rather uses the IP address.

**Comment by Smexhy** [comment]
Oh, I am sorry, I thought you are also the author of the homebridge plugin. I would contact him directly but his github repository is giving me 404 so I figured it may be you.

I suppose there is nothing you can do, it’s more likely issue with homebridge/homekit rather than yours, as it can find the PS4 just fine, but won’t let me change its state. I will try to find the developer and contact him directly. Thanks you.

**Comment by dhleong** [comment]
It's no problem. They might still want you to try using `ps4-waker` directly, as it could be a network config thing, so I would recommend trying the troubleshooting if you haven't yet. It could also be related to [this](https://github.com/dhleong/ps4-waker/issues/121) issue, which unfortunately seems to be beyond our control as it affects the official app, too.

**Comment by Smexhy** [comment]
Just wanted to let you know that using just your commands the ps4 wakes up and goes to stand by mode just fine. So it’s issue on the homebridge plugin.

**Comment by dhleong** [comment]
Gotcha, thanks for the follow up! Good luck!
