### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ulist** [dhleong/ps4-waker#125]
I were thought to make script to activate the ps4 from my device and make it looping because the electricity bad here 
Any idea?
Wrong place to ask ? Well idk
Thanks

**Comment by ulist** [comment]
This is what I was looking for Maybe?

**Comment by dhleong** [comment]
You're wanting the script to automatically start the device, then restart it whenever it gets turned off, is that correct?

You can definitely accomplish that with ps4-waker. You'll want to read a few tutorials on Javascript if you don't already know it, especially about `Promise` and `async/await` and node.j's `EventEmitter`. 

Your script will basically look like this:

1. Create a [Device](https://github.com/dhleong/ps4-waker/blob/master/lib/device.js)
1. Call `await device.turnOn()`; if it throws an error, wait a few seconds and try again
1. If you get a `'disconnected'` or `'error'` event from the device, go back to step 2

**Comment by ulist** [comment]
Copy and paste I hope :)
I know about nodejs but I forgot

**Comment by dhleong** [comment]
Sorry but I don't have time to write your code for you for free. There are
hundreds of quality Javascript tutorials out there these days so with the
right motivation anybody can learn. If you need some kind of reference, my
own personal home automation setup open-sourced here:
https://github.com/dhleong/my-home2.

These issues are not for general programming help. For that, try
stackoverflow.com or Google. But if you run into a ps4-waker-specific
issue, then I've been known to help with that in the past.

Good luck!
