### ISSUE TITLE
PS4-Waker No longer Shutting down only rest mode after firmware update

### ISSUE THREAD

**Issue by GuccW6** [dhleong/ps4-waker#129]
Not sure what has happened but prior to the latest firmware update the ps4 was shutting all the way down now it is only going into rest mode when I use the ps4-waker standby command?

**Comment by dhleong** [comment]
Sounds like Sony fixed a bug. The standby command is intended to put PS4
into rest mode; if it were to shut it down entirely, it would not be able
to wake it up again.

I'm not even aware of a command to remotely shut down the PS4 completely.

**Comment by GuccW6** [comment]
When I first installed it I expected it to only be able to wake up from rest as you explained but when I tested it was turning completely off and switching on from that state. The most recent firmware update seems to have made it function as it should then so I am happy to leave it there. Thank you again for being so responsive to me it is much appreciated.
