### ISSUE TITLE
Second Screen app cannot see ”PS4-Waker“ for initial setup

### ISSUE THREAD

**Issue by debug45** [dhleong/ps4-waker#131]
1. I switched on the PlayStation 4.
2. Then performed ”sudo ps4-waker“ and was instructed to launch the PS4 Second Screen app.
3. I launched the app, but the ”PS4-Waker“ was not displayed there, only my real PlayStation 4.

The console, computer, and phone with the app are all on the same wireless network. What could be the problem? Thanks.

**Comment by dhleong** [comment]
That is odd indeed. My only guess is it *could* be a network configuration issue. See [this troubleshooting section](https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#ps4-waker-cant-see-the-ps4). But the app can see the PS4, and ps4-waker can see the PS4, so I'm not sure why the app cannot see ps4-waker. Usually, if ps4-waker can find the PS4 then the app part should work fine...

**Comment by debug45** [comment]
Can I help you with collecting information about my problem?

**Comment by dhleong** [comment]
- Have you tried all the troubleshooting items?
- What OS are you running `ps4-waker` on?
- Does your `ps4-waker` device have more than one network adapter? (eg: connected to both ethernet and wifi)

**Comment by debug45** [comment]
1. Yes.
2. Raspbian Lite 4.19.
3. Wi-Fi only.

**Comment by dhleong** [comment]
Do you have another machine you can test with to see if the issue is your Raspbian device?

**Comment by dhleong** [comment]
This sounds crazy, but maybe try [resetting some of your network connections](https://github.com/dhleong/ps4-waker/issues/130#issuecomment-576645530)? That guy also had a bizarre situation that didn't make sense....

**Comment by DenFav** [comment]
I've got the same issue. Also read troubleshooting section. Also using Raspbian. 
Somehow I was able to got the pin request in terminal, but I even don't know hot it happened because PS4-Waker is not visible in the Screen share app
