### ISSUE TITLE
Failed state and ps4-waker not found

### ISSUE THREAD

**Issue by Tiempie** [dhleong/ps4-waker#132]
Hi I try to link ps-waker to homebridge but I have been unsuccessful. got this in my config:
`,
        {
            "platform": "cmdSwitch2",
            "name": "CMD Switch",
            "switches": [
                {
                    "name": "Playstation 4 PRO",
                    "on_cmd": "ps4-waker -c ~/homebridge/.ps4-wake.credentials.json",
                    "off_cmd": "ps4-waker -c ~/homebridge/.ps4-wake.credentials.json standby",
                    "state_cmd": "ps4-waker -c ~/homebridge/.ps4-wake.credentials.json search | grep -i '200 Ok'",
                    "polling": true,
                    "interval": 5,
                    "timeout": 2000,
                    "manufacturer": "Sony Corporation",
                    "serial": "03274525565653753",
                    "model": "CUH-7116B"
                }
            ]
        }`
But I get this in the console:
[3/11/2020, 8:34:02 AM] [CMD Switch] Failed to determine Playstation 4 PRO state.
[3/11/2020, 8:34:02 AM] [CMD Switch] /bin/sh: ps4-waker: not found
When I execute ps4-waker from terminal it does work, but the button in Apple Homekit does nothing

**Comment by dhleong** [comment]
Hi there, this is not the support forum for Homebridge, and though I'd like to help I know nothing about their system. If `ps4-waker` works from the terminal, that's as far as I can help here.

All I can offer is that homebridge is saying it can't find where you've installed ps4-waker. It may be running as a different user so its path is different from yours.

Good luck!
