### ISSUE TITLE
Ps4-Waker Working Great on Terminal, but on Homebridge dont work

### ISSUE THREAD

**Issue by hsismeiro** [dhleong/ps4-waker#135]
hello! i'm trying to get this work, but i cant, on Terminal it works great, i can Turn On/Off my ps4, but when i come to my iphone, it shows that my PS4 is On/Off, so i tried to turn off/on from the Iphone and it makes that error...
![ps4-waker 2](https://user-images.githubusercontent.com/61689872/76813082-c26ca980-67ee-11ea-9335-27bddf37fc00.png)
![ps4-waker](https://user-images.githubusercontent.com/61689872/76813084-c3054000-67ee-11ea-9127-e13111c42168.png)

**Comment by dhleong** [comment]
Hey there, this isn't the homebridge support forum, and in general if `ps4-waker` works from the command line there's nothing I can help with.

The only thing I can suggest here is that if homebridge is not running as your user then it may not be finding the credentials file, which could be causing it to try to initialize, requesting `sudo`. Try adding the `-c` flag to your `ps4-waker` invocations to ensure it's using the right config file, something like: `ps4-waker standby -c /users/yourusername/.ps4-wake.credentials.json` (but obviously with a real path for your system).
