### ISSUE TITLE
Ps4-Waker dont work on Homebridge 

### ISSUE THREAD

**Issue by tomcruces** [dhleong/ps4-waker#136]
Hi, PS4-waker work on the terminal, but I can't use this on homekit (homebridge). 

I started the application with "PS4-waker".

This is my configuration:

![Configuration](https://user-images.githubusercontent.com/63136803/78418252-f4647500-7610-11ea-96f9-e3beca40bc3e.PNG)

And the location of the credential is:

![credentials](https://user-images.githubusercontent.com/63136803/78418257-ffb7a080-7610-11ea-9cb2-6694992e1860.PNG)

Thank you for your support!.

**Comment by dhleong** [comment]
As I've said before, I'm not responsible for any homebridge or other
integrations; if it works at the CLI then that's my job done. You're better
off asking for help on the homebridge project.

That said, you could try using an absolute path for that "credentials"
config.

**Comment by tomcruces** [comment]
You are amazing!

I share the route for those who need it.

Question: does this only allow you to leave the PS4 in sleep mode? can i turn it off? 

![image](https://user-images.githubusercontent.com/63136803/78455959-80a98300-7677-11ea-90a4-398a3f0b081a.png)

**Comment by dhleong** [comment]
Glad it's working for you!

You can only put the PS4 to sleep—otherwise, you would not be able to wake it again!
