### ISSUE TITLE
launching by title-id

### ISSUE THREAD

**Issue by scramble45** [dhleong/ps4-waker#14]
Whenever I try to launch anything via title id it cannot find the application. Hitting ok takes me into the store where it shows the app I was trying to launch.

**Comment by dhleong** [comment]
What title id are you trying to use? I use these daily without issue:
https://github.com/dhleong/ps4-waker/wiki

**Comment by scramble45** [comment]
I tried the title-id for Plex and all the others listed in the wiki. On 3.55 PS4 firmware.

**Comment by dhleong** [comment]
Are you using it exactly as listed? It seems to be case sensitive. I did a clean install and auth with version 0.9.1 of `ps4-waker` and ran:

    ps4-waker start CUSA00129

and it worked without problem. However, running

    ps4-waker start cusa00129
    
did not find the netflix app, and prompted me to open the store

**Comment by scramble45** [comment]
Interestingly enough it just now started working with netflix and and hbo go but plex's title id: CUSA01703 - just says cannot find the application.

https://store.playstation.com/#!/en-gb/apps/plex/cid=EP4544-CUSA01703_00-WEBMAF000000PLEX

**Comment by dhleong** [comment]
Hmm. Judging from that url, I guess you have a UK PS4? This probably won't
work, but try with the USA title id for plex: CUSA01850. I just installed
Plex and it worked for me. Of course, I'm in the USA so it makes sense that
it'd work here... but it's worth a shot, if the USA ids for Netflix worked
for you.

**Comment by scramble45** [comment]
That was it, Im actually in the US but was using the wrong title-id. Thanks for the help. This is working great for me now. I was using their search and didn't notice that the store changed on me.

**Comment by dhleong** [comment]
Great! Glad it's working for you :)

**Comment by Krizzzn** [comment]
Here's a way to find the CUSA of every game one owns. Leaving this here, because I hope I can find it again in the future.

This is the library on the playstation network.

![Bildschirmfoto 2021-02-15 um 22 17 19](https://user-images.githubusercontent.com/439778/107994091-305fb900-6fdc-11eb-894d-8d0f47b40675.png)
