### ISSUE TITLE
WAKEUP sent to device...

### ISSUE THREAD

**Issue by gradyhouston** [dhleong/ps4-waker#143]
I had ps4-waker working but woke up this morning and for some reason, it wasn't being recognized by my Home app. So I tried deleting the credentials file and starting over but now when I run `ps4-waker` (sudo or not), I always get "WAKEUP sent to device... 192.168.1.18". I've tried removing the Mobile connection from the PS4, I've tried uninstalling the plugin completely and reinstalling, I've tried moving the credentials file. Nothing seems to get ps4-waker to start over cleanly.

**Comment by gradyhouston** [comment]
I managed to get a different outcome this time - I deleted the credentials file (again) from root directory and tried to pair it again with the Playstation Mobile app. PS4-waker in the app never connects. It just sits there at "connecting..." before timing out.

**Comment by dhleong** [comment]
We always send the WAKEUP to the device because this seemed to be necessary for it to start accepting TCP requests. That is expected output.

If the problem is that `standby` and other requests (except the default `wake`) aren't working, I suspect this is a Sony bug, as per my latest comment on #142

**Comment by gradyhouston** [comment]
Sure, I get that requirement of that. I finally got it to work but now it requires I run `ps4-waker` in the terminal every time I want to the PS4 to turn on. Homebridge says it's on, but it's not. It's like once it goes to sleep for a long period of time, it's not being awoken by any signal until I run `ps4-waker`.

**Comment by dhleong** [comment]
It's possible that because homebridge thinks it's awake, it is not
doing anything. I'm not associated with homebridge, so you'll have to take
that bit up with them. If ps4-waker works, that's all I can do for you.

**Comment by gradyhouston** [comment]
Well, the thing is it doesn't always work. Half the time when I run `ps4-waker` in terminal, I still get `Could not detect any matching PS4 device`. I have the credentials file in the correct place, too.

**Comment by dhleong** [comment]
Have you tried increasing the timeout? (-t flag)

**Comment by gradyhouston** [comment]
It's been set to 20000. That should be long enough, right?

**Comment by dhleong** [comment]
That depends on your network topology, possibly router, router config, etc.
I just use the default 10000 (10 seconds) and cannot recall it ever timing
out, except when the PS4 has just within the last few seconds gone to
sleep, but some people have reported that increasing the timeout helps.

How frequently and in what situations does it timeout? Have you compared
this performance with that of the official app?

**Comment by gradyhouston** [comment]
ps4-waker doesn't always show in the second screen app but maybe it doesn't need to. When I run `ps4-waker` in my terminal, it's kind of random when it works vs. when it doesn't. I just ran it right now and it woke it up just fine (even with my TV off), but last night, I was getting the `Could not detect any matching PS4 device` under the same conditions as right now. The timeout is currently set to `30000`. When I do get the `Could not detect any matching PS4 device`, it's usually after 5-10 seconds.

I'll keep trying. It's just not consistent for me, which I know you can't affect. Just mostly wanting to see if there's something I'm doing wrong with the plugin.

**Comment by dhleong** [comment]
What I mean is, does the second screen app consistently wake the PS4 in
situations where ps4-waker is timing out?

**Comment by gradyhouston** [comment]
Ah, no. The second screen app doesn't always see the PS4. I get "No PS4 found" a lot when the PS4 is off. The app is on the same network at the PS4.

**Comment by dhleong** [comment]
Ah, yeah in that case unfortunately there's probably nothing much I can do.
ps4-waker is based on the same protocols that app uses (by reverse
engineering) so in most cases we're limited by the functionality of that
app.

My best guess would be a router or router config issue; it's possible your
router is dropping packets sometimes. Maybe try checking for firmware
updates for your router?

**Comment by gradyhouston** [comment]
I'm not seeing any packet drops on the network. I'll keep playing with it. Thank you for the help here!
