### ISSUE TITLE
CMD/Dummy failed, not sure how to clear corrupt creds

### ISSUE THREAD

**Issue by andrewtlove** [dhleong/ps4-waker#15]
I can't seem to figure out where/how credentials are being stored.  Since I can't clear credentials, I'm unable to reattempt to connect with the iPhone app.  How would I go about clearing credentials so I could reattempt configuration?

**Comment by dhleong** [comment]
How did it fail? Any specific error message?

The credentials are stored by default in ~/.ps4-wake.credentials.json

If you could provide the contents of that file (please redact any tokens,
though!) I might be able to better handle this case.

**Comment by andrewtlove** [comment]
Sorry, I finally found the file in /root because in order to run ps4-waker dummy, I have to run with sudo privileges.  When I remove .ps4-wake.credentials.json and try again, I receive a `Unexpected error 14 LOGIN_FAILED` after giving ps4-waker the 8-digit PIN code showing on screen.  My credential file looks like the following:

```js
{ 'client-type': 'i',
  'auth-type': 'C',
  'user-credential': '<TOKEN REMOVED>' }
```

Thanks for your help! :)

**Comment by dhleong** [comment]
Hmm... Try moving the credentials file to your home dir (and update permissions so the normal user can access it) and running ps4-waker without sudo.

**Comment by andrewtlove** [comment]
That got me a bit further, however I'm now seeing this:

```bash
WAKEUP sent to device... 192.168.1.43
[Error: Device didn't wake in time]
```

I'm able to wake using the PS app as well as PlayCast, so I know my device is reachable on the network.

**Comment by dhleong** [comment]
I thought this sounded familiar. #9 ran into the same thing. You may need to delete these creds and try to re-pair. I think the PS4 ignores the WAKEUP packet if the token is invalid/unexpected.

**Comment by andrewtlove** [comment]
Got it figured out.  I'd accidentally paired my phone during the pairing step.  Looks like the device is uniquely identified and it will fail when trying to add a device with the same identifier.  These are the steps I followed for success after impairing my iPhone:

0. Turn on PS4
1. Run `sudo ps4-waker`
2. When prompted, attempt to pair with ps4-waker
3. When prompted, enter PIN code
4. Run `sudo cp -r /root/.ps4-wake.credentials.json`
5. Run `sudo rm /root/.ps4-wake.credentials.json`
6. Run `ps4-waker standby` to test.


Thanks again for your guidance, wouldn't have figured out my multiple errors without your help! 👍
