### ISSUE TITLE
Ps4-waker does not show up on my seconds screen app

### ISSUE THREAD

**Issue by AllSeeingGoatWizard** [dhleong/ps4-waker#151]
I have tried multiple tries to get this to work with no luck. Not too familiar with code so just following instructions point by point. Where might the issue be that Ps4-waker never pops up on my second screen app? I can get ps4-waker + ps4 waker platform to show power status without the credentials but no actions can be done.

**Comment by dhleong** [comment]
1. Does your actual PS4 show up on the app?
2. Have you followed everything here: https://github.com/dhleong/ps4-waker/wiki/Troubleshooting ?

**Comment by AllSeeingGoatWizard** [comment]
1. Yes my actual ps4 shows in my app. Deleted pairing and did it again to test it out. Pairing that way works
2. Probably not all of them no

**Comment by dhleong** [comment]
Try all of them :) I don’t have my device with me to test that Sony hasn’t
changed anything, but assuming they have not this is most likely either:


   1. A network/router configuration issue, so the app literally cannot
   “see” your computer
   2. A permissions issue, so ps4-waker cannot bind on the ports it needs
   to bind to in order for the app to “see” it

**Comment by AllSeeingGoatWizard** [comment]
Opening ports 987,997 did not make a difference. Also --bind-port didn't change a thing. Bind ip same thing

**Comment by dhleong** [comment]
Did you look at https://github.com/dhleong/ps4-waker/issues/112 ?

**Comment by AllSeeingGoatWizard** [comment]
Problem fixed. It seemed to be a limitation on pizero. I upgraded to Pi4 and installed like a charm.

**Comment by dhleong** [comment]
Glad to hear! Was the port blocked on the older software or something?

**Comment by AllSeeingGoatWizard** [comment]
To be honest I don't know what it was. I did the full list of stuff you guided me to do and nothing. Switched to pi4 and boom everything went works on the first try .LoL

**Comment by dhleong** [comment]
Fair enough! I've updated the Wiki to link to this in case anybody else runs into this. Thanks for your help debugging this!
