### ISSUE TITLE
Problem after resting ps4 Slim

### ISSUE THREAD

**Issue by RoSo7** [dhleong/ps4-waker#152]
So, after trying everthing, I ended up having always the same problem.
I managed to configure everthing as the instructions, but as soon as I turn my console to resting mode, I'm only able to communicate with it for a couple of seconds, after that, the "no matching PS4 found" error shows up
I've tried the --device option, --bind options as well and ended the same way.
I filmed a video showing the problem but I couldn't attach it. I can email you if needed

**Comment by dhleong** [comment]
How long did you wait after putting it to sleep before trying again? When the PS4 is put into rest mode it becomes unresponsive for a minute or so before you can wake it again. Also—are you sure you're putting it in rest mode/standby and not shutting it down? A few users have asked about that and the answer is it can only be awoken from rest/standby mode. if powered off, there is no way to wake it other than by physically touching it.

**Comment by RoSo7** [comment]
After putting to sleep, I've waited different times, 10 minutes, up to a whole night.
Yes, i am. Also, I only use the standby command to do it

**Comment by dhleong** [comment]
Have you tried everything here? https://github.com/dhleong/ps4-waker/wiki/Troubleshooting

Also: 

1. What happens when you run `ps4-waker search`? 
2. In this state, can the Second Screen app see/interact with the device?

**Comment by RoSo7** [comment]
1- same response "could not detect any matching PS4 device"
2- what "state" you mean? The "PS4-waker" in the second screen app, only showed once. And once I like, closed the app, or waited to long, it disappeared.

**Comment by dhleong** [comment]
> 2- what "state" you mean? The "PS4-waker" in the second screen app, only showed once. And once I like, closed the app, or waited to long, it disappeared.

I mean, in the situation where `ps4-waker search` cannot find your PS4, is the Second Screen app able to find it?

**Comment by RoSo7** [comment]
Ohh yes, in the app, my actual PS4 appears

**Comment by dhleong** [comment]
Have you followed every step in https://github.com/dhleong/ps4-waker/wiki/Troubleshooting ?

There's a whole section on "ps4-waker can't see the PS4."

**Comment by RoSo7** [comment]
So, I've tried every topic in "troubleshooting", and I figure something new.
In the configuration process, I managed to connect with the app, but when I close the app, the "PS4-waker" device vanishes, is this normal?
Second, I don't know what to do anymore, if you can help me by doing a step by step to see if I'm missing something, I woud appreciate a Looooot

**Comment by RoSo7** [comment]
I think there's something wrong in my console, cause when I turn it off, I cant see it in my app at all

**Comment by RoSo7** [comment]
Another thing that happens and I don't know if it's normal, is that when I run "ps4-waker", with my ps4 turned on, it shows that I've connected with an complementary app, and right after it shows that I disconnected

**Comment by RoSo7** [comment]
As I were wrinting those last comments, I finally figure out, it seems that my playstation only stay connected in wifi while I'm literally using the internet, so both the app and the program only work when I'm downloading something

**Comment by RoSo7** [comment]
I don't know other way to fix it

**Comment by RoSo7** [comment]
Finally find out the problem, but dont know how to fix it.
The problem is that my PS4 cant stay connected, if there is nothing beeing downloaded.
When there is something actually using the internet connection, the program works lke a charm.
Any tips about how to solve it?
Btw, in PS4 config, the "stay connected to internet" and "Tur on thru app" options are enabled

**Comment by dhleong** [comment]
It sounds like, from your deleted comments, this is an issue either with the PS4's firmware or your router, since the official app also cannot see the device when you put it in standby mode. If the official app cannot see it, there's not much ps4-waker can do, since they use the same protocol.

> The problem is that my PS4 cant stay connected, if there is nothing beeing downloaded.

Does this mean even when the PS4 is on, it has trouble staying connected to the internet? Are you connected to your router via wifi? Have you tried an ethernet cable? I found [this comment](https://www.reddit.com/r/PS4/comments/akh587/ps4_wont_stay_connected_to_the_internet_any/ef562rc/) that sounds potentially promising.

**Comment by RoSo7** [comment]
I have not tried via cable cause my router is in another room. 
While PS4 is on, i don't have any problem staying connected in the app

**Comment by codyc1515** [comment]
Only with Ethernet does it work for me. Are you using wifi?

**Comment by RoSo7** [comment]
Yes, I'm. But, I've foud a way to do it using Wi-Fi

**Comment by codyc1515** [comment]
How?

**Comment by RoSo7** [comment]
Try going to the settings and set the PS4 to go to rest mode automatically after some time of inactivity

**Comment by RoSo7** [comment]
For me it worked like a charm
