### ISSUE TITLE
Could not detect any matching PS4 device

### ISSUE THREAD

**Issue by NexusBRYT** [dhleong/ps4-waker#153]
I started the Installation, using `npm i ps4-waker -g`, then proceeded to connect the console to the Second Screen app, but when i executed `ps4-waker`, it gave me the `Could not detect any matching PS4 device` error.

Any solutions? (My 3 devices are connected to the same network, PC and PS4 with cable and phone with wifi, also tested the PS4 with Wi-fi but doesn't work either)

**Comment by dhleong** [comment]
Have you followed all the steps here? https://github.com/dhleong/ps4-waker/wiki/Troubleshooting

**Comment by NexusBRYT** [comment]
using `-bind <ip>` to specify the adapter worked, thanks for the help!
