### ISSUE TITLE
Error message WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained

### ISSUE THREAD

**Issue by Ms-Sudo** [dhleong/ps4-waker#156]
Hi, when installing ps4-waker on homebridge I am getting the following warnings:

_npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been 
deprecated in favor of separate inclusion of a polyfill and 
regenerator-runtime (when needed). See the @babel/polyfill docs 
(https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained 
and not recommended for usage due to the number of issues. Please, 
upgrade your dependencies to the actual version of core-js@3._

I've researched the internet but cannot make sense of it as I don't know much about linux. 

I am also getting the warning that the plugin slows down homebridge: "_[homebridge-ps4-waker-platform] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info._"

I am running the latest version of homebride with 
Node.js Version v14.16.1
Npm Version v7.9.0

**Comment by dhleong** [comment]
The deprecation warnings can be ignored, or you can switch to using https://github.com/dhleong/playactor/. 

As for the homebridge stuff, I don't maintain homebridge plugins and don't use homebridge so I don't have any advice there. My guess is that it's complaining that scanning for the status of the device is slow, which there's not much I can do about; the device responds at its own pace. But again, your best bet is to reach out to the maintainer of `homebridge-ps4-waker-platform`.

Are you encountering any issues with the behavior of `ps4-waker`, or just reporting these warnings?

**Comment by Ms-Sudo** [comment]
Thank you for your quick reply. 
So far I only have those warnings. 

Sorry if this was the wrong place to report my problem.

**Comment by dhleong** [comment]
> So far I only have those warnings.

If there are no functional issues I'm going to go ahead and close this issue, but feel free to open a new one if you run into a problem!

> Sorry if this was the wrong place to report my problem.

Not a problem :)

> EDIT: I am running PS4-Waker now as a child bridge and get no warnings/error messages. I updated core-js before. But I cannot find any way to figure out which version of core-js is installed. Is there a command or a trick? Any help is appreciated.

I'm not sure how you're set up, but if you're using `npm` you can do `npm ls` to see the graph of dependencies and versions
