### ISSUE TITLE
Limit search to specific device?

### ISSUE THREAD

**Issue by RobotLimeLtd** [dhleong/ps4-waker#16]
Can the search function be restricted by IP?  Alternatively, could the JSON output be formatted as one line per device?  

I'm trying to integrate this to homebridge, but with more than one PS4 on the network, it's difficult to ascertain the status of an individual machine.

**Comment by dhleong** [comment]
The `-d` flag should let you specify an IP address. Is there a command it doesn't work with?

Depending on what you're using this for, I might recommend using the library directly. It's not quite as high-level as the cli program (yet...) but might be easier to to get at whatever you're interested in.

**Comment by dhleong** [comment]
Closing in favor of #17
