### ISSUE TITLE
Add firewall rules to troubleshooting tips

### ISSUE THREAD

**Issue by Greenoliv** [dhleong/ps4-waker#162]
Hi! My problem was that the PS4Waker device wasn't showing up in the Second Screen app. I used an iPhone with a Windows notebook. I thought I tried everything. Set the Wi-Fi as Private, run the command in an admin cmd, a non-admin cmd, reconnected the WiFi, but nothing. But! When I added port 987, 997 and 999 as allowed inbound and outbound UDP ports, in the Windows Firewall settings, it immediately showed up. So I recommend to allow these ports for the time of the login. Steps:
- Search "Windows Defender Firewall with Advanced Security"
- Click "Inbound Rules" on the left
- Click "New Rule..." on the right
- Select "Port"
- Next
- Select "UDP" and "Specific remote ports"
- Type "987, 997, 999"
- Next
- Click "Allow this connection"
- Next
- Next
- Give it a name
- Finish
- Repeat the same steps with Outbound rules

**Comment by dhleong** [comment]
Thanks! I added a link directly to your description here
