### ISSUE TITLE
Control specific device via -d flag not working

### ISSUE THREAD

**Issue by RobotLimeLtd** [dhleong/ps4-waker#17]
The -d flag to specify a particular PS4 by its IP address is not working - I set up two PS4 systems in my house as per the instructions (although noticing that the created ~/.ps4-wake.credentials.json file was identical for each).

When I run ps4-waker with the -d flag, it always tries to start/stop the first system I set up, completely ignoring the IP address I have passed.

**Comment by dhleong** [comment]
Ah, that'd be a bug then. I only have one myself, so I don't test that
regularly. At some point maybe I'll refactor things to be more testable,
but since it works for my purposes I don't think about it....

I'll look into this as soon as I can.

**Comment by RobotLimeLtd** [comment]
It works for switching the PS4 on only, but not for the arguments search, standby, remote or start.

**Comment by dhleong** [comment]
Got it, thanks.

**Comment by RobotLimeLtd** [comment]
Ok - I've been testing a bit more... seems that the problem only occurs when I don't also specify the timeout option.  Add the timeout option at the command line and it works perfectly, e.g.:

ps4-waker -d 192.168.1.5 -t 500 standby

ps4-waker -d 192.168.1.5 -t 500 search

etc.

So there's a very easy workaround - sorry to waste your time!

**Comment by dhleong** [comment]
Not a problem. Still a bug so I'll still fix it, but glad it's working for
you in the meantime. Thanks for your help debugging!

**Comment by dhleong** [comment]
Just released version 1.0.0 that should fix this. Please let me know if you still encounter issues.
