### ISSUE TITLE
Device must be awake for initial registration. Please turn it on manually and try again.

### ISSUE THREAD

**Issue by LeakDotIn** [dhleong/ps4-waker#170]
`pi@raspberrypi:/var/lib/homebridge $ ps4-waker
Device must be awake for initial registration. Please turn it on manually and try again.
pi@raspberrypi:/var/lib/homebridge $ sudo ps4-waker
Device must be awake for initial registration. Please turn it on manually and try again.
pi@raspberrypi:/var/lib/homebridge $ `

anyone can help me? I'm on raspberry pi zero and installed via `sudo npm i ps4-waker -g`

**Comment by dhleong** [comment]
Have you manually turned on your PS4 before running that command per the error message?

See also: https://github.com/dhleong/ps4-waker/wiki/Troubleshooting

**Comment by LeakDotIn** [comment]
> Have you manually turned on your PS4 before running that command per the error message?
> 
> See also: https://github.com/dhleong/ps4-waker/wiki/Troubleshooting

no

**Comment by dhleong** [comment]
> no

Then there's your answer :) Turn on the PS4 the old-fashioned way then try again. It is not possible to perform the registration necessary to enable ps4-waker to do its thing without the PS4 being fully "on."

I also recommend you try running `ps4-waker` without `sudo`; doing so has been known to cause issues in the past. It should invoke sudo if it needs to (and let you know that it's going to)
