### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by knockreff** [dhleong/ps4-waker#21]
Running as Raspberry Pi3 unable to install

`
> ursa@0.9.4 install /usr/local/lib/node_modules/ps4-waker/node_modules/ursa
> node-gyp rebuild

>make: Entering directory '/usr/local/lib/node_modules/ps4-waker/node_modules/urs                                                                                             a/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
In file included from ../src/ursaNative.h:10:0,
                 from ../src/ursaNative.cc:3:
../node_modules/nan/nan.h:324:47: error: ‘REPLACE_INVALID_UTF8’ is not a member                                                                                              of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
>ursaNative.target.mk:84: recipe for target 'Release/obj.target/ursaNative/src/ur                                                                                             saNative.o' failed
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/ps4-waker/node_modules/ursa                                                                                             /build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:                                                                                             23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:                                                                                             12)
gyp ERR! System Linux 4.4.13-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ps4-waker/node_modules/ursa
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

>npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/ps4-waker/node_module                                                                                             s/async/node_modules/lodash/fp/reduceRight.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

>npm ERR! System Linux 4.4.13-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "ps4-waker" "-g"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/ps4-waker/node_modules/async/node_modu                                                                                             les/lodash/fp/reduceRight.js
npm ERR! fstream_path /usr/local/lib/node_modules/ps4-waker/node_modules/async/n                                                                                             ode_modules/lodash/fp/reduceRight.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

>npm ERR! System Linux 4.4.13-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "ps4-waker" "-g"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
`
'

**Comment by dhleong** [comment]
Since it's ursa, it's probably #18 ; see my response in #20. Closing for now but feel free to reply if the update (coming by Monday ish, probably) doesn't fix things for you.

**Comment by dhleong** [comment]
Released 1.0.1; as above, let me know if the change does not fix the problem for you.
