### ISSUE TITLE
SyntaxError: Unexpected token...

### ISSUE THREAD

**Issue by joeperrin** [dhleong/ps4-waker#22]
I have installed ps4-waker on Windows 10.

It seems to install without issue but when I attempt to run the executable "ps4-waker" with no arguments I get the following output error:

![2016-10-25_22-23-21](https://cloud.githubusercontent.com/assets/1489569/19714282/ba2915aa-9b01-11e6-9459-72bd70a15b60.png)

PS C:\ps4> ps4-waker
C:\Users\joe\AppData\Roaming\npm\node_modules\ps4-waker\bin\cmd.js:107
    var keyNames = argv._.slice(remote).map((key) => key.toUpperCase());
                                                                               ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
PS C:\ps4>

Any ideas whats happening here?

Thank you!

**Comment by dhleong** [comment]
Looks like you're using an older version of node. Try updating.

**Comment by joeperrin** [comment]
> Looks like you're using an older version of node. Try updating.

That fixed it. I was using a really old version of node. Updated to the latest LTS and it seems to be working now. 

![powershell_2016-10-26_12-59-02](https://cloud.githubusercontent.com/assets/1489569/19743097/ae6a3ec6-9b7c-11e6-99da-576d624e9cb2.png)

Thanks for the help!

**Comment by dhleong** [comment]
No problem!
