### ISSUE TITLE
Unable to find any matching PS4 devices

### ISSUE THREAD

**Issue by exleyd** [dhleong/ps4-waker#23]
what must i try to do with the app? Am I supposed to run just ps4-waker and then try and connect the app? Thanks

**Comment by dhleong** [comment]
You're going to have to provide some more information. What have you tried specifically? What error message are you getting? What platform are you on?

When I get time I may look into automating this, but what most people seem to have to do is:

```
// launch with root privileges to be able to get the auth tokens
$ sudo ps4-waker
// move the tokens so you don't need root
$ cd ~
$ sudo mv /root/.ps4-wake.credentials.json .
// run again without root
$ ps4-waker
```

**Comment by exleyd** [comment]
Okay I'm running on openWRT Linux.
The message I get is after a few seconds - unable to find any matching PS4 devices

During these few seconds I'm trying to connect my PlayStation app.

I don't have the credentials file you mention.

**Comment by exleyd** [comment]
I can ping the PlayStation 4 from Linux as they are all on same LAN. But always get error - could not detect any matching PS4 device.

**Comment by dhleong** [comment]
Does your machine have multiple network interfaces?

**Comment by exleyd** [comment]
Yes it's a router. so the like the following
root@OpenWrt:~# ifconfig
br-lan    Link encap:Ethernet  HWaddr C0:56:27:B5:4A:3C
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fd7e:b62c:61bd::1/60 Scope:Global
          inet6 addr: fe80::c256:27ff:feb5:4a3c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4117040 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4730457 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:332816109 (317.3 MiB)  TX bytes:9967529664 (9.2 GiB)

eth0      Link encap:Ethernet  HWaddr C2:56:27:B5:4A:3C
          inet addr:86.4.11.183  Bcast:86.4.11.255  Mask:255.255.255.0
          inet6 addr: fe80::c056:27ff:feb5:4a3c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:10894984 errors:0 dropped:4 overruns:0 frame:0
          TX packets:3993808 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:532
          RX bytes:10344872260 (9.6 GiB)  TX bytes:373632257 (356.3 MiB)
          Interrupt:194

eth1      Link encap:Ethernet  HWaddr C0:56:27:B5:4A:3C
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1148419 errors:0 dropped:8 overruns:0 frame:0
          TX packets:1293481 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:532
          RX bytes:77752732 (74.1 MiB)  TX bytes:3207125448 (2.9 GiB)
          Interrupt:195

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:36227 errors:0 dropped:0 overruns:0 frame:0
          TX packets:36227 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2670007 (2.5 MiB)  TX bytes:2670007 (2.5 MiB)

wlan0     Link encap:Ethernet  HWaddr 00:25:9C:13:C3:34
          inet6 addr: fe80::225:9cff:fe13:c334/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2950653 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4873513 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:311544186 (297.1 MiB)  TX bytes:2638227729 (2.4 GiB)

wlan1     Link encap:Ethernet  HWaddr 00:25:9C:13:C3:33
          inet6 addr: fe80::225:9cff:fe13:c333/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:62899 errors:0 dropped:0 overruns:0 frame:0
          TX packets:67313 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:7777912 (7.4 MiB)  TX bytes:26667240 (25.4 MiB)

**Comment by dhleong** [comment]
Yep, okay so you're probably going to need to use the `-b` flag to pick which adapter to use.

**Comment by exleyd** [comment]
Okay I got a bit further. Unfortunately my system hung when I was trying to enter the code from the playstation. Now it keeps saying  ps4-518 is already awake when I try to run set up again

**Comment by dhleong** [comment]
Try running `ps4-waker standby -b (ip)` to see if the credentials worked.
If not, you can delete and try again. They should be at
~/ps4-wake.credentials.json, or in /root if you haven't moved them.

**Comment by exleyd** [comment]
I retried and it reported that the credentials were created. Although I can't get it to standby or wake up. For wake up it just times out.

**Comment by dhleong** [comment]
Times out never finding the PS4? Did you try moving the credentials and run
without root like I suggested early? What is the exact output in both cases?

**Comment by exleyd** [comment]
Got credentials! { 'client-type': 'i',
  'auth-type': 'C',
  'user-credential': '032e62effb4369824437a54f74350b36915180a441a71dd347be104bae68a37f' }
Logged into device! Future uses should succeed

In the app it still says its connecting for PS4-waker

**Comment by exleyd** [comment]
Finally the app reports Cannot connect to the PS4 within the time limit

**Comment by exleyd** [comment]
root@OpenWrt:/# ps4-waker -d 192.168.1.194
WAKEUP sent to device... 192.168.1.194
[Error: Device didn't wake in time]

**Comment by dhleong** [comment]
Don't forget `-b` every time. When not specified, it uses the "first" adapter returned by the system, the behavior of which is unreliable. The only other thing I can think of would be to ensure the ports are accessible. I've never tried running from a router. I believe the ports used are 997 and 987

**Comment by exleyd** [comment]
Ok thanks, I got a bit close with...

root@OpenWrt:~#  ps4-waker -d 192.168.1.194 -b 192.168.1.1
WAKEUP sent to device... 192.168.1.194
Logging in...
Login connect refused; retrying soon
Done!

**Comment by exleyd** [comment]
It connected when the playstation was on and I saw the notification on the tv screen.

root@OpenWrt:~#  ps4-waker -d 192.168.1.194 -b 192.168.1.1
WAKEUP sent to device... 192.168.1.194
Logging in...
Done!

But when the playstation is in rest mode, I got the following
root@OpenWrt:~#  ps4-waker -d 192.168.1.194 -b 192.168.1.1
WAKEUP sent to device... 192.168.1.194
[Error: Device didn't wake in time]

**Comment by exleyd** [comment]
I called this command while the ps4 was going in to rest mode. 
Interesting because it does locate the IP of the playstation.

root@OpenWrt:~#  ps4-waker -b 192.168.1.1
WAKEUP sent to device... 192.168.1.194
[Error: Device didn't wake in time]

But if i run the same command when in rest mode without specifying the IP I get the following

root@OpenWrt:~#  ps4-waker -b 192.168.1.1
[Error: Could not detect any matching PS4 device]

**Comment by dhleong** [comment]
The playstation won't respond for a few seconds after you start putting it
into rest mode. Detecting the device works by broadcasting a udp packet on
the network, so it's possible trying to do that from the router is
problematic due to some configuration. This doesn't sound like a problem on
ps4-waker's side, though.

**Comment by exleyd** [comment]
Yeah its strange that this works 

root@OpenWrt:~# ps4-waker -d 192.168.1.194 -b 192.168.1.1
WAKEUP sent to device... 192.168.1.194
Logging in...
Done!

But I cant remote key, standby or search to work

**Comment by dhleong** [comment]
What happens when you try to do those?

**Comment by exleyd** [comment]
ps4 was on when I ran both of these....

root@OpenWrt:~#  ps4-waker failfast -d 192.168.1.194 -b 192.168.1.1 standby
Could not detect any matching PS4 device


root@OpenWrt:~#  ps4-waker -d 192.168.1.194 -b 192.168.1.1 remote ps
Could not detect any matching PS4 device

**Comment by dhleong** [comment]
Okay, so when just waking the device, if the IP is provided we try to "detect" it, and just assume we can reach the IP---this is why it tries to send WAKEUP when it was already awake; normally it will just tell you that there's no need to wake. The specific actions, however, depend on getting a response from the device. I might consider doing the same for regular actions, but basically your problem is that either the router is not (consistently) delivering outgoing UDP packets to port 987, or (probably more likely) you're not (consistently) getting the UDP responses. 

If you don't mind getting your hands dirty, you might try changing the `undefined` here: https://github.com/dhleong/ps4-waker/blob/master/lib/detector.js#L51 to some port number that you explicitly open to local traffic on your router, and see if that gets you any further.

**Comment by exleyd** [comment]
That sound right because almost immediately after it says "companion app connected to playstation" on my TV screen it says "disconnected companion app". 

I've tried all sorts of port numbers in the detector js but no joy yet.

**Comment by exleyd** [comment]
The companion app never fully connects and is just left "connecting...."

**Comment by dhleong** [comment]
> The companion app never fully connects and is just left "connecting...."

That's normal; it's trying to log in over a socket, but we don't have the PS4's private key, so we can't encrypt a real response. As long as the `ps4-waker` says it got the credentials, it should be good to go....
