### ISSUE TITLE
Can't start PS4 Walker

### ISSUE THREAD

**Issue by outrun0506** [dhleong/ps4-waker#24]
Hi,

i just installed nodejs + ps4-waker on a rPI3.

If i try to run ps4-waker I'm getting following error:

```
pi@pi:/home $ sudo ps4-waker

/usr/local/lib/node_modules/ps4-waker/bin/cmd.js:107
    var keyNames = argv._.slice(remote).map((key) => key.toUpperCase());
                                                   ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Any help?

**Comment by dhleong** [comment]
You're using an older version of nodejs. Is a more recent version available for your platform?

**Comment by outrun0506** [comment]
Good questiom just installed it via apt-get

Von meinem Huawei-Mobiltelefon gesendet

-------- Originalnachricht --------
Betreff: Re: [dhleong/ps4-waker] Can't start PS4 Walker (#24)
Von: Daniel Leong
An: dhleong/ps4-waker
Cc: outrun0506 ,Author


You're using an older version of nodejs. Is a more recent version available for your platform?

-

**Comment by outrun0506** [comment]
Update nodejs to 7.0.0 now its working. Thanks a lot.
