### ISSUE TITLE
Can go to standby but won't wake up

### ISSUE THREAD

**Issue by exleyd** [dhleong/ps4-waker#25]
Hi, I can go to standby just fine using the command, but each time I try to do a wake up I get "error: could not get any matching PS4 device

**Comment by exleyd** [comment]
I'm running on pi 3

**Comment by dhleong** [comment]
What command are you using to go to standby, what command to wake it up, and how long after putting it to sleep are you trying to wake it up?

**Comment by exleyd** [comment]
For standby: PS4-walker standby
For wake: PS4-wake (returns could not detect any matching PS4 device) I've also tried with sudo. 
More than 5 mins elapsed after putting the PS4 to sleep

**Comment by exleyd** [comment]
Okay I realised what I had missed. I had not turned on "allow turn on ps4 from network" setting in ps4's power management settings.  All working now :-) Thanks for all your help!

**Comment by dhleong** [comment]
Glad it's working for you :)
