### ISSUE TITLE
Need to specify discovery port

### ISSUE THREAD

**Issue by kylerw** [dhleong/ps4-waker#26]
I'm receiving: 

Error: Could not detect any matching PS4 device
    at Detector.<anonymous> (/usr/local/lib/node_modules/ps4-waker/lib/detector.js:124:18)
    at emitNone (events.js:86:13)
    at Detector.emit (events.js:185:7)
    at Detector.close (/usr/local/lib/node_modules/ps4-waker/lib/detector.js:83:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by dhleong** [comment]
Okay:

1. How are you invoking `ps4-waker`? 
1. What platform?
1. Is the PS4 on?
1. Does the machine you're running from have multiple network adapters?
1. Have you ensured your router will let through UDP packets to/from port 987 and 997 on the PS4?
1. Have you turned on the "Allow turn on PS4 from network" setting in the PS4 Power Management settings?

**Comment by kylerw** [comment]
I've tried: 

- ps4-waker
- sudo ps4-waker
- sudo ps4-waker -b 192.168.1.188 
- sudo ps4-waker -b 192.168.1.188 -d 192.168.2.15

PS4 was on. I am running in Docker (which has mapped the UDP ports) and their are multiple network adapters (hence the -b). I have allowed the traffic across VLANs and opened up the router.

Allow turn on is enabled on the PS4.

**Comment by dhleong** [comment]
The detection process sets up a udp server on an undefined port. I bet
what's happening is the incoming port isn't mapped to your Docker instance
so it can't find any device. If you feel comfortable editing
lib/detector.js, try specifying a port on line 50 and mapping that and see
if that works. If it does, I'll add a flag so you can specify it on cli.

**Comment by kylerw** [comment]
@dhleong hmmm, not sure where you are referring as line 50 is in the comment... do you mean line 51, 'undefined'?

**Comment by dhleong** [comment]
It's the first undefined on the non-comment line with `bind` there. I'm on
mobile so it could be a bit off. You're probably looking at the right
thing.

**Comment by kylerw** [comment]
Yeah, that seemed to work. It's now asking me to connect to PS4-Waker but now the mobile app can't find it or my PS4....

**Comment by dhleong** [comment]
You said there are multiple network adapters.... Is your mobile app on the
same LAN adapter with the device running ps4-waker? Or can you set up such
a route?

This sounds like a networking issue, rather than a problem with the library
(besides the port thing, which I will build into the code when I get a
chance). If the official app can't even see the real PS4 then you have some
router configuration to do.

**Comment by kylerw** [comment]
Yep, I managed to sort out the routing issues and all is good. A command line option to select the port would be excellent!

**Comment by dhleong** [comment]
Awesome, glad to hear! I'll get on that flag ASAP.

**Comment by dhleong** [comment]
Released version 1.1.0 with `--bind-port` option

**Comment by mreassassin** [comment]
I’m thinking this may be my issue too. How do I open up ports in my router?  My ps4 app can power in the ps4 but ps4-waker can’t find it. Also tried all the mentioned above methods. Thinking it’s in the router side like this issue.

Please help. 
Thanks!

**Comment by BOverdevest** [comment]
I also get the "Could not detect any matching PS4 device". I have PS4-waker running on a Raspberry.
Strange thing is I can ping all kind of devices from the CLI on the the Pi, but cannot ping the PS4.
If I try the same from my laptop, i can reach the PS4.  So, definitely a network issues, but I got no clue how to resolve it....
