### ISSUE TITLE
Playstation app only finds PS4, not PS4-Waker

### ISSUE THREAD

**Issue by mbardelmeijer** [dhleong/ps4-waker#27]
As the title says, the playstation app can only find my PS4. `ps4-waker` is running with the message 'No credentials; Use Playstation App and try to connect to PS4-Waker' but no luck. Refreshed the 'Second Screen' multiple times, even tried reinstalling the app.

Have tried binding it to my LAN or WiFi adapter on my Windows machine, but no luck (running it on Bash on Windows)

Have also tried running it on a raspberry pi, but got the 'Could not detect any matching PS4 device' error there.

All tests have been on the same subnet. Can succesfully ping my iPhone from my Windows machine & the raspberry pi.

**Comment by dhleong** [comment]
Sounds like router config. Have you looked through? https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#your-network-is-dropping-udp-packets

**Comment by mbardelmeijer** [comment]
Worked it out! Didn't work on Bash on Windows (due to what i think) is a incomplete network implementation. Didn't work on the PI due to firewall constraints. Added the UDP ports on the PI and it worked like a charm. Thanks!

**Comment by dhleong** [comment]
Glad to hear!
