### ISSUE TITLE
Does not detect PS4 Pro

### ISSUE THREAD

**Issue by oorahduc** [dhleong/ps4-waker#28]
I have a PS4 and a PS4 Pro in my house, with ps4-waker on macOS Sierra 10.12.

When running 'ps4-waker search', it will always return the state of my regular PS4 in standby mode, but never identify the PS4 Pro which is on.

**Comment by dhleong** [comment]
Without any other arts, `ps4-waker search`

**Comment by oorahduc** [comment]
You're a gentleman, and a scholar.
