### ISSUE TITLE
Remote OnScreenKeyboard support

### ISSUE THREAD

**Issue by stratosnn** [dhleong/ps4-waker#29]
Hi,
Ps4-waker is great tool especially with new key press support. I find it very handy for automating certain tasks. What I miss is support for remote on screen keyboard. Basically to be able to send text input to PS4. This feature is present in official PS4 companion app. I'm happy to contribute with this patch myself, however I need some help :) You were able to reverse engineer remote control flow sequence by some means and I hope you could give a hint on how I can do the same with OSK.

I have tried to sniff traffic between PS4 and companion app, however I could not find the way to decrypt the messages correctly. What I know is that client should send message indicating its interest in OSK event and then there will be status(?) message response from PS4 indicating OSK input is enabled. I think there is an option for client to pull for this event as well.

**Comment by dhleong** [comment]
See #10 where I talked about how I got it. 

Good luck!

**Comment by HansWurst90** [comment]
Do the remote keys only work in the PS Menu?
In Netflix they don't work for me.

**Comment by dhleong** [comment]
@HansWurst90 That's correct. I believe you'll find that they don't work even from the official Playstation App.

**Comment by HansWurst90** [comment]
@dhleong okay, thank you. Just wanted to make sure I'm not doing something wrong.
Thanks for such a great tool though!

**Comment by dhleong** [comment]
No problem :)

**Comment by dhleong** [comment]
Begin experimenting with this feature. Got some basic stuff working in the `dhleong/osk` branch, for anyone curious. Only working through `Device`/`Socket` right now; no CLI interface

**Comment by dhleong** [comment]
Published as 1.3.0. See README for CLI interface. It's pretty rudimentary
