### ISSUE TITLE
Unexpected error 20 PASSCODE_IS_NEEDED

### ISSUE THREAD

**Issue by mtandrup** [dhleong/ps4-waker#3]
When I execute ps4-maker I get the following message:
No credentials; Use Playstation App and try to connect to PS4-Waker

I connect to PS4-Waker from the app and ps4-waker gives me this message:
Got credentials! { 'client-type': 'i',
  'auth-type': 'C',
  'user-credential': 'xxxxxxxxxxxxxxxxx' }
Unexpected error 20 PASSCODE_IS_NEEDED

My setup is:
Windows 8.1
iPhone 6 with iOS 8.1.3
PlayStation App v. 2.0.7
PS4 software v. 2.04

**Comment by dhleong** [comment]
Interesting. I've never actually encountered the `PASSCODE_IS_NEEDED` message so I'm not sure what to do with it.

Could you try changing your `client-type` from `i` to `a`? The file should be stored in your home directory as `.ps4-wake.credentials.json`. It may be the iOS clients use passcode verification instead of pin....

**Comment by mtandrup** [comment]
I can't seem to do that.

I actually have to delete the .ps4-wake.credentials.json file every time I execute ps4-waker.
If I don't, ps4-waker keeps saying "[Error: undefined is already awake!]" every time I launch it.

**Comment by dhleong** [comment]
Oh, right, because it has credentials already. Hmm...

**Comment by dhleong** [comment]
I just published 0.4.2 which works for me (I was able to reproduce your error). Please update this ticket with further information if it still doesn't work

**Comment by mtandrup** [comment]
Now I can connect succesfully to the PS4.

However when I try to wake up my PS4, it still says that the PS4 is already awake.

**Comment by dhleong** [comment]
Woops! 0.4.3 incoming
