### ISSUE TITLE
PS-app doesn't connect to PS4-waker

### ISSUE THREAD

**Issue by m3lvn** [dhleong/ps4-waker#30]
Hi, I'm not able to connect the iPhone app to the waker. It keeps "connecting".

I am able to control the playstation via the raspberry terminal with your commands and succesfully registered the given key.

Any idea why I can't connect with the app? Cause I can't control the playstation with neither iOS Home or Eve.

Thanks!

**Comment by dhleong** [comment]
That's what's supposed to happen, actually.

If the ps4-waker terminal commands are working... you've done everything
right. iOS Home support is beyond the scope of this project.
