### ISSUE TITLE
Likely same issue #25

### ISSUE THREAD

**Issue by ajowen** [dhleong/ps4-waker#32]
Hi,
ps4-waker standby works every time
but if I using ps4-waker to wake up, it shows below 

 `WAKEUP sent to device... 192.168.0.120
Error: Device didn't wake in time
    at loop (/usr/lib/node_modules/ps4-waker/index.js:295:26)
    at /usr/lib/node_modules/ps4-waker/lib/detector.js:142:13
    at Detector.<anonymous> (/usr/lib/node_modules/ps4-waker/lib/detector.js:120:26)
    at emitTwo (events.js:106:13)
    at Detector.emit (events.js:191:7)
    at Socket.<anonymous> (/usr/lib/node_modules/ps4-waker/lib/detector.js:60:18)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)`

"But sometimes it work perfect" Don't know how

I'd turned on "allow turn on ps4 from network" setting in ps4's power management settings.

**Comment by dhleong** [comment]
> "But sometimes it work perfect" Don't know how

Are you saying that this error does not happen every time? Sometimes the device wakes correctly?

Have you tried everything here: https://github.com/dhleong/ps4-waker/wiki/Troubleshooting

**Comment by ajowen** [comment]
Thanks for reply 
Now, I'm able to wake up  after putting the PS4 to sleep more than 30 mins

**Comment by dhleong** [comment]
> after putting the PS4 to sleep more than 30 mins

So any sooner than that and you get the above error? 30 minutes is a bit long, but it's normal to not be able to wake your PS4 immediately after putting it to sleep. As long as it's flashing orange, it's still doing stuff to get ready for sleep and won't respond to network requests. Sometimes even for a little bit after.

**Comment by ajowen** [comment]
I'm trying redo the credentials step. But how to find the json file and delete it on raspberry pi 3.
Sorry, I'm a newbie here.

**Comment by dhleong** [comment]
See: https://github.com/dhleong/ps4-waker/wiki#credentials

**Comment by ajowen** [comment]
Sorry.. I have a stupid questions.
On the terminal in my raspberry pi. I try to `rm /root/.ps4-wake.credentials.json`
But it shows permission denied .

**Comment by dhleong** [comment]
You ran ps4-waker as root, so the file is owned by root, but you're trying
to delete it as a normal user. Try:

sudo rm /root/.ps4-wake.credentials.json

**Comment by ajowen** [comment]
Finally, after I delete it and repair. It works perfect.
Thank you so much

**Comment by dhleong** [comment]
No problem. Glad it's working for you!
