### ISSUE TITLE
Quit Title?

### ISSUE THREAD

**Issue by HansWurst90** [dhleong/ps4-waker#33]
It's awesome to be able to start title, but is there also way to quit a running title?

**Comment by dhleong** [comment]
You can use `ps4-waker remote ps` to send the ps menu button. That's all we can do right now. I haven't used it in a while, but I don't think the official app has a "quit title" function?

**Comment by HansWurst90** [comment]
I was just wondering. Is the `ps4-waker start title` directly from the app.
Cause I didn't know you could start games from the app.

Thanks anyways. I still can't believe what a great tool that is.
It's awesome for home automation :-)

**Comment by dhleong** [comment]
There doesn't appear to be a way to explicitly quit an app.

There is theoretically a way to hold buttons, however it's not currently exposed to the CLI. You'd have to get your hands dirty with the Javascript API. I'll open a separate ticket to consider exposing "hold duration" to the cli

**Comment by dhleong** [comment]
See #34

**Comment by dhleong** [comment]
@HansWurst90 I've released v1.2.0 which has support for holding a button via the CLI, and via the new `Device` API if you want to use Javascript.
