### ISSUE TITLE
Works perfectly when ps4 is already running, but i cant get it to wake her from rest-mode

### ISSUE THREAD

**Issue by davidblumer** [dhleong/ps4-waker#36]
`Logged into device! Future uses should succeed
➜  ~ ps4-waker standby
Standby requested`
`ps4-waker
[Error: Could not detect any matching PS4 device]`

even with ip-address
`ps4-waker --device 192.168.178.31
WAKEUP sent to device... 192.168.178.31
[Error: Device didn't wake in time]`

what am i missing out?

**Comment by dhleong** [comment]
https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#ps4-waker-can-put-the-ps4-to-sleep-but-not-wake-it-up

Also:

https://github.com/dhleong/ps4-waker/issues/32

**Comment by dhleong** [comment]
Closing due to no response in a month
