### ISSUE TITLE
How can I reset the ip set by the flag -d?

### ISSUE THREAD

**Issue by hhhlau** [dhleong/ps4-waker#37]
I think I screw things up when I am doing the first pairing up and I would like the restart everything...
But no matter I reinstall how many time the pre-set ip by the flag -d is keeping in my Pi and the error "PS4 is already awake! (Ok)" keep popping out...

How could I start everything from fresh again?? (now I no longer can search "ps4-waker" in my ps app)

**Comment by dhleong** [comment]
The `-d` flag doesn't save anything anywhere. That message means it connected to the PS4 and it said it was awake. The "Ok" is part of the response from the device.

See: https://github.com/dhleong/ps4-waker/wiki/Troubleshooting

**Comment by dhleong** [comment]
Closing due to no response in a month
