### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by CoalaJoe** [dhleong/ps4-waker#38]
Hey there, I noticed when using your tool that one does not get valid JSON.

Is this something on your side or the API of the PS4?

When using other programming-languages, it is hard to decode invalid JSON.

Here is what I get (Github will probably cry about the format aswell):
```json
{ type: 'device',
  statusLine: '200 Ok',
  statusCode: '200',
  status: 'Ok',
  'host-id': 'BC60A766BA99',
  'host-type': 'PS4',
  'host-name': 'PS4',
  'host-request-port': '997',
  'device-discovery-protocol-version': '00020020',
  'system-version': '04550011',
  'running-app-name': 'Curses \'N Chaos',
  'running-app-titleid': 'CUSA03106',
  address: '192.168.1.75' }
```

![image](https://cloud.githubusercontent.com/assets/5689499/25585604/af883846-2e9b-11e7-9737-6c07e279b03e.png)

**Comment by dhleong** [comment]
The cli interface is not really designed for that sort of use right now.
You'll have better luck using the Javascript API directly.

**Comment by CoalaJoe** [comment]
@dhleong I know. 
So is this problem on this repo or the PS4 API?
