### ISSUE TITLE
device.js requires node 7.10 (or 7.5 with the --harmony flag)

### ISSUE THREAD

**Issue by Neuroplant** [dhleong/ps4-waker#41]
/usr/lib/node_modules/ps4-waker/lib/device.js:110
    async getDeviceStatus() {
          ^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/ps4-waker/bin/cmd.js:4:14)

Running on Raspian
node v6.10.3
npm 3.10.10

or doing it something wrong?

**Comment by dhleong** [comment]
Woops. Looks like I misread how available async functions are. Can you install node v7?

**Comment by dhleong** [comment]
Specifically 7.10+. 

Given that version isn't a LTS (and the 8.0 LTS doesn't start until October) I may need to look into a cross-piling down to support node 6....

**Comment by apexad** [comment]
You may be able to just bring in babel as well to support the `async` function.

**Comment by Neuroplant** [comment]
Many Thanks!
Updated node.js to v7.10.0 and it works fine now.
(I don't understand what "---harmony flag" means)
[https://www.npmjs.com/package/ps4-waker/tutorial](url) guides you to the wrong node.js Version, mayby you can change this tutorial?

Neuroplant

**Comment by dhleong** [comment]
Glad to hear!

I don't know if I have control over that tutorial, but I'm planning to release an update later today that'll make things "just work" for node 6 like you originally had.

**Comment by dhleong** [comment]
Released v1.2.1 which supports Node 6 LTS.
