### ISSUE TITLE
cant turn on ps4

### ISSUE THREAD

**Issue by ins4neuk** [dhleong/ps4-waker#48]
for some reason i cant get the ps4 to turn on but i can standy it.

when i run "sudo ps4-waker" i get "could not detect any matching ps4 device"

yet when i run "sudo ps4-waker standy" when i'm logged in i get wakeup sent to device and it turns off...

any suggestions

**Comment by dhleong** [comment]
https://github.com/dhleong/ps4-waker/wiki/Troubleshooting

Specifically:

https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#ps4-waker-can-put-the-ps4-to-sleep-but-not-wake-it-up

**Comment by ins4neuk** [comment]
thanks a lot. working a treat now and a nice little app.  added the alexa node to my node-red flow with the execute node so i can now turn on or off the ps4.. even when the kids are on it and should be going to bed :D

**Comment by dhleong** [comment]
Glad to hear!
