### ISSUE TITLE
Unexpected error:21 / LOGIN_FAILED

### ISSUE THREAD

**Issue by Mashewnutz** [dhleong/ps4-waker#51]
Hi I am trying to get ps4-waker to work but not having much luck.

This is what I am doing:
1) Turn on PS4
2) Launch PSApp on my phone
2) rm ~/.ps4-wake.credentials.json
3) sudo ps4-waker
4) Connect to ps4-waker from PSApp from my phone via second screen menu
5) Credentials are received
6) goto Settings->PSApp Connection Settings -> Add Device
7) Enter 8digit passcode
8) LOGIN_FAILED

Here is the output (The x's are actually real credentials):

Matthews-MBP:Projects Mash$ sudo ps4-waker
No credentials; Use Playstation App and try to connect to PS4-Waker
Got credentials!  { 'client-type': 'i',
  'auth-type': 'C',
  'user-credential': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' }
Go to 'Settings -> PlayStation(R) App Connection Settings -> Add Device' on your PS4 to obtain the PIN code.
Pin code> 65403635
Unexpected error:21 / LOGIN_FAILED

Any ideas what I can try?

**Comment by dhleong** [comment]
Hmmmm... I'm not at home to be able to test myself but your steps look about right. It looks like you have valid credentials, though, so maybe skip the pairing step and try the `--pin` flag?

**Comment by Mashewnutz** [comment]
I tried with the --pin flag but that didn't work either:
Matthews-MBP:Projects Mash$ sudo ./node_modules/ps4-waker/bin/cmd.js --pin 8800
Unexpected error:21 / LOGIN_FAILED

I also tried this:
Matthews-MBP:Projects Mash$ sudo ./node_modules/ps4-waker/bin/cmd.js
WAKEUP sent to device... 192.168.1.149
Logging in...
Login error: LOGIN_FAILED

**Comment by Mashewnutz** [comment]
OK I have sorted it! I was signed into the mobile app with a different account than the ps4 was using. I successfully put it into standby and also woke it! Great this thing is amazing! Next step is to hook it up to Alexa 👍

**Comment by dhleong** [comment]
Fantastic, glad you figured it out! I'll add this to the Troubleshooting page.
