### ISSUE TITLE
Shutdown or exit game

### ISSUE THREAD

**Issue by KozmoK** [dhleong/ps4-waker#54]
Can this code be used to simulate a ps4 shutdown, or exit game?

I am trying to control the use of my 12 year old and his ps4  He has x hours a day to play on it.  I don't want to restrict via router in a block of time. 
my pi program will allow him to start/stop the timer.  After his time is expired, I'd like to send a remote exit/shutdown. I'd like to control the powerplug via relay module, and a shutdown first would be nice.

**Comment by dhleong** [comment]
Check our the `standby` command in the usage help. You could also use the
`remote` command to send the `ps` key press to exit a game, but standby is
probably the stronger option, since otherwise you can just tap the PS
button again to get back into the game.
