### ISSUE TITLE
Unexpected token" error

### ISSUE THREAD

**Issue by gid204** [dhleong/ps4-waker#56]
Hey, I know this is a troubleshooting step in the wiki (very sorry about that)

My nodes version is 4.8.4 and thats why I cannot run ps4-waker.

I've been trying to update/uninstall & reinstall to get at least version 6/8 but no matter what I do it defaults back to 4.8.4.

I'm following the instructions on the official site with no luck!
any guidance would be greatly appreciated!

**Comment by dhleong** [comment]
This is not really the place for advice on installing nodejs and I don't know what sort of hardware you're running on, but I can give it a shot.

Can you install the `n` package?

    npm install -g n

Then you should be able to just do

    n latest
    
See: https://github.com/tj/n

**Comment by gid204** [comment]
That did it, thanks a lot!!!
