### ISSUE TITLE
Add wake without login

### ISSUE THREAD

**Issue by thomaspurchas** [dhleong/ps4-waker#58]
I've been trying to find an easy way to wake a PS4 without also logging in. Currently everything assumes that you want to login after waking, and seems to be quite difficult to make it optional.

I've already looked at the `autologin` param on the Waker API, but all of the higher level stuff like that `Device` objects all assume it's `true` which makes it very difficult to expose. Any idea on the easiest way to expose awake-without-login at the cmd level?

**Comment by dhleong** [comment]
Interesting. I didn't include the option because I couldn't imagine a situation you would want that, but it should be easy enough to add an option to the Device API and forward a CLI flag.

Do you mind if I ask what your use case is for this?

**Comment by thomaspurchas** [comment]
Pretty simple, got a flat with multiple flatmates, each has their own account. It's nice if the PlayStation can be left on the login screen at wake, but hardly a deal breaker :).

I currently have a Harmony remote waking the PS4 via HomeAssistant and ps4-waker, to work around the fact the remote has no native support for waking a PS4

**Comment by dhleong** [comment]
Fair enough! I'll try to find some time to throw this together for you.

As another option, you could use multiple credentials files, if each profile is associated with a separate psn account, so each user can log into their own account.

**Comment by thomaspurchas** [comment]
Thanks!

Unfortunately multiple credentials doesn't work as I have no way of asking who's there :(

**Comment by dhleong** [comment]
Don't know how the harmony remote works, but you could maybe have a bunch of separate different buttons ;)

**Comment by dhleong** [comment]
@thomaspurchas Just released v1.4.0 with the `--skip-login` cli flag. Enjoy :)

**Comment by thomaspurchas** [comment]
Totally awesome! Thanks for that dude!
