### ISSUE TITLE
Won't run from shell script via REST API

### ISSUE THREAD

**Issue by slappula** [dhleong/ps4-waker#61]
I have ps4-waker installed on an Ubuntu machine.  It works fine when I'm SSH'd in and manually type ps4-waker.  Is setup Apache and a REST server and have a PHP script that calls the shell script.  It seems like this is all getting to the point where the ps4-waker command is executed, because I had some permissions errors that were being written to the Apache error log.  Once I resolved those, I don't see any more errors (but it doesn't wake the PS4).  Are there ps4-waker specific logs I should be checking?

**Comment by dhleong** [comment]
Is Apache running as the same user that you configured ps4-waker as? If not, you'll want to point the exe to the location of the config files using the `-c` flag. 

`ps4-waker` doesn't log anywhere besides `stdout`/`stderr`.

For something like this, you'll probably have an easier time using node.js and using the `Device` API.

**Comment by slappula** [comment]
Thanks dehleong, the -c flag did it!  I started down the road of using node.js, but that has to be called with curl, right?  I want to integrate with Samsung SmartThings, so I'm planning to use WebCore to make a call via REST.  I don't think I have an option to access the Device API using either SmartThings or WebCore (but I'd love to be proven wrong).

Also- thanks so much for ps4-waker!

**Comment by dhleong** [comment]
node.js is just another technology. I don't know anything about WebCore and haven't used PHP in ages, but you said you just need to receive a REST call? That's (basically) just any old HTTP service, which node.js can definitely spin up. cURL just performs HTTP calls, so you could trigger your PHP thing with it as well.

You're correct that you can't directly access the Device API using SmartThings or WebCore; you would create your REST service in node.js, and access it from there. One nice advantage of that method is that you can create the Device instance once and have your HTTP call handlers control it; this would mean you can use methods like `sendKeys()` and `startTitle()` without getting a bunch of "Device connected... Device disconnected" messages.

But, whatever works for you ;)
