### ISSUE TITLE
PS4 Remote Play

### ISSUE THREAD

**Issue by grill2010** [dhleong/ps4-waker#62]
Hi, I'm writing you because I really like your work with the ps4-waker and it is really useful.
Did you ever consider to try  to connect to the PS4 as a remote play device?
I'm the creator of a remote gamepad app for Windows and I constantly get requests to emulate a Dualshock controller for PS4.  As first try I'm currently trying to archive this by reverse engineering the remote play APK. However it is highly obfuscated and some of the functions are in a native library. It is theoretically possible because a guy called twisted built an unofficial remote play software for PCs. He is charging for his software and I can not blame him for because it is working really well. However, I think it would be better to release this kind of protocol for the community so that several people can work on it, trying to keep it up to date.
The PS4 app is unfortunately very limited in its functionality. One of the biggest issues is that you can not send real Dualshock buttons with the PS4 app as far as I know. Do you think it would be possible or do you have already some experience with that?

**Comment by dhleong** [comment]
Not with this library, unfortunately. The key press API offered by the Playstation App is, as you surmised, very simplistic, limited, and slow. I don't have any experience with the Remote Play functionality, either. My best guess for a place to start would be to use Wireshark and observe the packets going by and look for patterns, but I'd bet they're encrypted, which makes things tricky....

Good luck!
