### ISSUE TITLE
No credentials; Use the PS4 Second Screen App and try to connect to PS4-Waker

### ISSUE THREAD

**Issue by andocromn** [dhleong/ps4-waker#66]
I'm trying to setup ps4-waker on a linux machine, raspberry pi to be specific.  I have installed nodejs 9.2.1 and ps4-waker seems to execute, however I have not been able to connect it to the PS4.  when I execute it, I receive a message "No credentials; Use the PS4 Second Screen App and try to connect to PS4-Waker" however it never asks for a pin code.  If I specify the code by command line with --pin it just results in the same message.  I have tried going in to the Second screen app on my android phone, which seems to be working fine but I don't see anything that would assist in setting up ps4-waker.

is there something i'm missing?

thanks in advance

**Comment by andocromn** [comment]
nevermind

**Comment by simonrb2000** [comment]
I'm having this issue.. This used to work but stopped so deleted the credentials file and trying again. Stuck on the above bit
