### ISSUE TITLE
start [titleId]

### ISSUE THREAD

**Issue by andreypolyak** [dhleong/ps4-waker#7]
How does start [titleId] feature works? I've tried all options which I can come up with as titleId and no one works.
Can I open YouTube or Plex using this feature?

Thanks!

**Comment by dhleong** [comment]
Yes, you absolutely can! I have my Amazon Echo hooked up to this library and use it to switch between Netflix, Youtube, and Amazon Video.

I've added a wiki entry that describes this, with a few examples that you can try:

https://github.com/dhleong/ps4-waker/wiki

**Comment by beaumartinez** [comment]
For those looking, you can discern the title ID from the URL in the PS4 store; eg, for GTA V, its store link is https://store.playstation.com/#!/en-gb/games/grand-theft-auto-v/cid=EP1004-CUSA00411_00-GTAVDIGITALDOWNL (UK link; will not work in all regions); the title ID is `CUSA00411`.

**Comment by dhleong** [comment]
👍 Thanks for the info! I've added it to the Wiki
