### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by MartinHelmut** [dhleong/ps4-waker#72]
Hey, I would like to contribute a bit more to the tool. Therefore it would be nice to have a contribution guide explaining how to develop and release.

Maybe this https://github.com/felixge/open-source-contribution-guide could be a help to start with? I would like to help with this but I'm a bit confused for example about the in python written build tool or how you want to handle stuff 😊

**Comment by dhleong** [comment]
There's not really much guidance to offer, but I can look into that. 

The `release.py` is for publishing releases with version notes, nothing to do with building. All you need to build should be `npm install` ;)

**Comment by MartinHelmut** [comment]
Ohh okay, yeh not only meant but release :) I was just wondering why not using a pre publish hook for npm. But in that case I would make a first PR with a suggestion for contribute guide.
