### ISSUE TITLE
PS4 needed to be restored to default settings, and now I can't pair again

### ISSUE THREAD

**Issue by C-Dub87** [dhleong/ps4-waker#77]
How do I start the pairing process again? PS4-Waker worked great until I had to restore my PS4 via safe mode, and now I need to re-pair it, but I don't know what to do.

**Comment by dhleong** [comment]
Delete the credentials file as described here: https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#error-device-didnt-wake-in-time
