### ISSUE TITLE
Synology

### ISSUE THREAD

**Issue by fibigod** [dhleong/ps4-waker#83]
Does anybody know if this can be installed on a synology nas? I'd like to use it with domoticz.

**Comment by dhleong** [comment]
This is not really the place for that sort of question, and I don't know anything about either of those things, but if you can install nodejs then the answer is a definite maybe.

**Comment by fibigod** [comment]
Ok thanx

**Comment by ColinOppenheim** [comment]
It can be done via Docker. I am currently running a Home Assistant docker container with the PS4 Waker installed in the same container. I'm still working on the operation through home assistant but that's just a matter of time. The PS4 waker runs via CLI without issue.  I'm not familiar with domoticz but i'm sure you could do the exact same thing as I am attempting to do with Home Assistant.

**Comment by fibigod** [comment]
Damn. I will try it soon. My NAS died yesterday. So I have to reinstall the whole system. Thanx for the tip.

**Comment by fibigod** [comment]
@ColinOppenheim 

I've installed node.js version 6
and then installed ps4-waker trough ssh.

And i can confirm it works of the CLI directly from the nas.

**Comment by johnsills1** [comment]
Can someone walk me through this.  I have a Synology and want to add a Shortcut to Siri that will turn my PS4 on/off. Not very technical, but I do have some reasonable knowledge.

**Comment by dhleong** [comment]
I don't have any experience with either of those things, but if anyone has a clear set of instructions I'd be happy to add the info to the wiki.

**Comment by dave-castle** [comment]
> @ColinOppenheim
> 
> I've installed node.js version 6
> and then installed ps4-waker trough ssh.
> 
> And i can confirm it works of the CLI directly from the nas.

installed nodev6 and ps4-waker on Synology NAS via ssh, when starting ps4-waker I receive following error:

`node ps4-waker
module.js:471
    throw err;
    ^

Error: Cannot find module '/ps4-waker'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
`
