### ISSUE TITLE
Update pairing instructions to match latest firmware

### ISSUE THREAD

**Issue by mok-liee** [dhleong/ps4-waker#85]
Hello, 

i try to pair my PS4 Pro with ps4-waker, but after asking the pair pin and typing in the correct 8 digit (split after 4 digits) he said:

`Go to 'Settings -> PlayStation(R) App Connection Settings -> Add Device' on your PS4 to obtain the PIN code.
Pin code> xxxxxxxx
Unexpected error:23 / LOGIN_FAILED`

i try to enter pin "xxxx xxxx" and "xxxxxxxx", i am realllllly sure that i type in the correct pin. What i am doing wrong?

greetings mok

**Comment by dhleong** [comment]
Thanks for the heads up!
