### ISSUE TITLE
Installing on Hassbian via SSH or Samba

### ISSUE THREAD

**Issue by rotcop4u2** [dhleong/ps4-waker#86]
I would like to install PS4-walker to be able to monitor and control my kids PS4 usage. Is there anyway to be able to have the install in apt-get command or possible directions on placement of the install via Samba file share?

thank you

**Comment by dhleong** [comment]
I don't know anything about Hassbian but if you can install an appropriate version of nodejs, you can instal `ps4-waker`. Try https://nodejs.org/en/download/package-manager/

**Comment by mqtt-fan** [comment]
check this out @rotcop4u2: https://community.home-assistant.io/t/ps4-waker-hass-io/28937/14
