### ISSUE TITLE
ps4 wont start, but after manual start everything works

### ISSUE THREAD

**Issue by Cino2424** [dhleong/ps4-waker#89]
I cant start my own PS4 with the tool. But after I turn on the ps4 manually everthing works.

pi@raspberrypi:~ $ sudo ps4-waker
Could not detect any matching PS4 device

**Comment by Cino2424** [comment]
I start with sudo and in energy option wake up over lan is enabled

**Comment by dhleong** [comment]
https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#ps4-waker-can-put-the-ps4-to-sleep-but-not-wake-it-up

**Comment by Cino2424** [comment]
IT is enabled

**Comment by dhleong** [comment]
Did you try these others on there? https://github.com/dhleong/ps4-waker/wiki/Troubleshooting#ps4-waker-cant-see-the-ps4

**Comment by Cino2424** [comment]
thx, worked with bind options. but one more question.

I think the only way to wake up is it to put the ps4 in standby or?

**Comment by dhleong** [comment]
That's correct. If the PS4 isn't at least in standby mode then it can't receive the wake instructions.
