### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Saudumm** [dhleong/ps4-waker#9]
I paired it with the PS4 App and got the credentials. ps4-waker search shows my ps4 correctly.

But every time I try to wake it up, this is all I get:

WAKEUP sent to device...
[Error: Device didn't wake in time]

If I try to send my PS4 to standby, this is the output:

{ [Error: Unable to go standby:11] status: 11 }

Any advice? (I'm on firmware 3.50)

**Comment by dhleong** [comment]
Router configuration seems most likely. My PS4 is also on 3.50 and I can't
reproduce your problem....

**Comment by Saudumm** [comment]
Router is configured to automatically open needed ports per device. Starting my PS4 via the mobile app is working fine. Is there a way to re-pair ps4-waker and the PS4 app?

**Comment by dhleong** [comment]
Cached credentials are stored at `~/.ps4-wake.credentials.json`. If you
delete that file, it should try to pair again.

**Comment by Saudumm** [comment]
Thanks. Mine was under /root but I deleted it, re-paired and got the prompt for a pin code (didn't get that prompt the first time). Now everything is working fine. :)

**Comment by dhleong** [comment]
Glad to hear!

**Comment by mreassassin** [comment]
I'm accessing my pi through putty and filezilla.  doing a search for '.ps4-wake.credentials.json' comes up empty.  I've tried uninstalling and reinstalling with no luck.  can somebody point me in the right direction?  My ps4 was working fine at one point then I added my xbox's to the mix (through cmdswitch2).  now ps4 doesn't get found.
