### ISSUE TITLE
Using Crediential File in Code

### ISSUE THREAD

**Issue by mqtt-fan** [dhleong/ps4-waker#96]
I use ps4 waker in my node app.

`const {Device} = require('ps4-waker');
var ps4 = new Device();`

is there an option to set the path to the credientials file?

Background: I want to dockerize my app :-)

**Comment by dhleong** [comment]
The code for `Device` is fairly well documented: https://github.com/dhleong/ps4-waker/blob/master/lib/device.js

TLDR:

```javascript
const device = new Device({
  credentials: "path/to/credentials.json"
});
```

**Comment by mqtt-fan** [comment]
thank you for the fast answer.

**Comment by dhleong** [comment]
No problem!
