### ISSUE TITLE
Device API

### ISSUE THREAD

**Issue by jaylow360** [dhleong/ps4-waker#99]
Hi, before anything else : congratulations and thanks for this tremendous work @dhleong !!!!
I'm not reporting a bug here , since I've been using your script ( running on Raspberry Pi ) to turn on and off a PS4 from my Home Automation system , for more than two months now ! Never had any issue yet !
Now I need to take it to the next level , by using the " device API" as you are suggesting for navigation and transports commands since this specific commands can't be used with the basic script because of the "open connection / command / close connection" behavior.
I know pretty much nothing about JS & / or json , and after more than two months trying to understand this " device API " on my own without asking anyone here , I'm now facing the truth : I REALLY NEED SOMEONE TO EXPLAIN IT TO ME ! 
Any help would be great , to explain me the main concepts of this "device API" so I can use it ! 

Thanks a lot !

**Comment by dhleong** [comment]
It sounds like you want to start with a general Javascript tutorial, which is somewhat out of scope for this forum. [This](https://javascript.info/) seems like an okay resource, and you will in particular want to understand how [asynchronous](https://javascript.info/async) Javascript works, especially [Promises](https://javascript.info/promise-basics) and [async/await](https://javascript.info/async-await). I've also heard good things about the [Grasshopper app](https://play.google.com/store/apps/details?id=com.area120.grasshopper&hl=en_US).

Once you have those tools under your belt, the device API should be pretty straightforward to use, it just all depends on what you're trying to do.
